# Generated by Django 2.0.2 on 2018-03-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='entities',
            field=models.ManyToManyField(to='history.Entity'),
        ),
    ]
